/**
 * React-based "Add Skill" / "Edit Skill" form, built with Fluent UI 9
 * (`@fluentui/react-components`) controls — same architecture as
 * src/ms-exam.tsx.
 *
 * Renders into #credpl-skill-form-root (see
 * Credpl_Admin_Skills::render_edit_page()) and submits as a plain HTML form
 * POST to admin-post.php — the `credpl_save_skill` handler
 * (Credpl_Admin_Skills::save()). Two editable fields, Skill Name and
 * Description, each a plain Fluent UI `Input`/`Textarea` forwarding its
 * `name` prop to the native control. The GUID is generated by PHP on first
 * save and is never shown or edited here.
 *
 * Initial values come from `window.credplSkillForm`, localized by PHP.
 */

import { createRoot, useState } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import {
	FluentProvider,
	webLightTheme,
	Field,
	Input,
	Textarea,
	Button,
	type InputOnChangeData,
	type TextareaOnChangeData,
} from '@fluentui/react-components';
import { useSkillStyles } from './styles';

/**
 * The shape PHP's `wp_localize_script( 'credpl-skill-form',
 * 'credplSkillForm', […] )` call sends (see
 * Credpl_Admin_Skills::enqueue_edit_form_assets()). `id` is a top-level
 * scalar, which `wp_localize_script()` stringifies (see the note on this in
 * src/credential.tsx) — typed `string` here for the same reason.
 */
interface SkillFormConfig {
	id: string;
	nonce: string;
	actionUrl: string;
	skillName: string;
	description: string;
	listUrl: string;
}

declare global {
	interface Window {
		credplSkillForm?: SkillFormConfig;
	}
}

const config: SkillFormConfig = window.credplSkillForm || ( {} as SkillFormConfig );

/**
 * Same bug this guards against as toNumber() in credential.tsx: `id: 0`
 * arrives here as the string `"0"`, which is truthy.
 */
function toNumber( value: string | undefined ): number {
	return Number( value ) || 0;
}

const initialId = toNumber( config.id );

function SkillForm() {
	const styles = useSkillStyles();

	const [ skillName, setSkillName ] = useState( config.skillName || '' );
	const [ description, setDescription ] = useState( config.description || '' );

	return (
		<FluentProvider theme={ webLightTheme }>
			<form method="post" action={ config.actionUrl } className={ styles.form }>
				<input type="hidden" name="action" value="credpl_save_skill" />
				<input type="hidden" name="id" value={ initialId } />
				<input type="hidden" name="_wpnonce" value={ config.nonce } />

				<Field label={ __( 'Skill Name', 'credentials-manager-plugin' ) } required>
					<Input
						className={ styles.control }
						name="skill_name"
						value={ skillName }
						onChange={ ( ev, data: InputOnChangeData ) => setSkillName( data.value ) }
						required
					/>
				</Field>

				<Field label={ __( 'Description', 'credentials-manager-plugin' ) }>
					<Textarea
						className={ styles.control }
						name="description"
						rows={ 6 }
						value={ description }
						onChange={ ( ev, data: TextareaOnChangeData ) => setDescription( data.value ) }
					/>
				</Field>

				<div className={ styles.actions }>
					<Button appearance="primary" type="submit">
						{ initialId
							? __( 'Update Skill', 'credentials-manager-plugin' )
							: __( 'Add Skill', 'credentials-manager-plugin' ) }
					</Button>
					{ config.listUrl && (
						<Button
							appearance="secondary"
							onClick={ () => {
								window.location.href = config.listUrl;
							} }
						>
							{ __( 'Back to All Skills', 'credentials-manager-plugin' ) }
						</Button>
					) }
				</div>
			</form>
		</FluentProvider>
	);
}

const root = document.getElementById( 'credpl-skill-form-root' );

if ( root ) {
	createRoot( root ).render( <SkillForm /> );
}
